#!/usr/bin/env python3
#coding:utf-8
"""
  Author:  Steve Barnes --<steven.barnes@bakerhuges.com>
  Purpose: Create build timestamp file
  Created: 01/11/21
"""

import datetime
import getpass

def gen_timestamp_file():
    """ Generate a file containing the build information."""
    ts = f"Built: {datetime.datetime.now().isoformat()} by {getpass.getuser()}"
    with open("build_info.py", 'wt') as outfile:
        outfile.write("# AUTOGENERATED FILE DO NOT EDIT\n")
        outfile.write(f'BUILD_INFO = "{ts}"\n')
    print("Build Information Generated")

if __name__ == '__main__':
    gen_timestamp_file()
